# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
      providers:
          in_memory:
              memory:
                  users:
                      donald:
                          password: 111111
                          roles: 'ROLE_ADMIN'
      encoders:
          Symfony\Component\Security\Core\User\User: plaintext

      firewalls:
          main:
              anonymous: ~
              http_basic: ~
          oauth_token:
              pattern:  ^/oauth/v2/token
              security: false

          secured_area:
              pattern:    ^/php bin/console config:dump-reference web_profiler
              fos_oauth:  true
              stateless:  true

      access_control:
          - { path: ^/, roles: [ IS_AUTHENTICATED_FULLY ] }

