# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
      providers:
          in_memory:
              memory: ~

      firewalls:
          oauth_token:
              pattern:  ^/oauth/v2/token
              security: false

          secured_area:
              pattern:    ^/
              fos_oauth:  true
              stateless:  true

      access_control:
          - { path: ^/, roles: [ IS_AUTHENTICATED_FULLY ] }