<?php

namespace UserBundle\Repository;

/**
 * RegistrationInfoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RegistrationInfoRepository extends \Doctrine\ORM\EntityRepository
{
}
